steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - '--dockerfile=Dockerfile'
      - '--destination=${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/nvitopia:$BUILD_ID'
      - '--destination=${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/nvitopia:latest'
      - '--cache=true'
      - '--cache-ttl=168h'
      - '--snapshot-mode=redo'
      - '--compressed-caching=false'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  # If E2_HIGHCPU_8 quota is unavailable, fall back: E2_HIGHCPU_4 → E2_HIGHCPU_2 → remove machineType

substitutions:
  _AR_REGION: us-central1
  _AR_REPO: cloud-run-source-deploy

timeout: 1200s
